FROM node:20-bullseye

# Устанавливаем необходимые build-зависимости для Strapi и нативных модулей
RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    automake \
    zlib1g-dev \
    libpng-dev \
    nasm \
    bash \
    libvips-dev \
    git \
    python3 \
    && rm -rf /var/lib/apt/lists/*

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/app

COPY package*.json yarn.lock* ./

RUN yarn global add node-gyp
RUN yarn config set network-timeout 600000 -g && yarn install --frozen-lockfile

ENV PATH /usr/app/node_modules/.bin:$PATH

COPY . .

RUN chown -R node:node /usr/app
USER node

RUN ["yarn", "build"]

EXPOSE 1337

CMD ["yarn", "develop"]