name: GOL-VUE-Strapi-prod

services:
  cms:
    build:
      context: ../cms
      dockerfile: ../prod-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms/public/uploads:/usr/app/public/uploads
      - ../cms/.tmp:/usr/app/.tmp
    restart: unless-stopped
    networks:
      - golnet
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    environment:
      # Strapi секреты
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}

      # Настройки приложения
      NODE_ENV: ${NODE_ENV}

      # Настройки SQLite
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      DATABASE_SSL: false

      # Настройки MySQL
      # DATABASE_HOST: db
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_USERNAME: ${DATABASE_USERNAME}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_CLIENT: mysql
      # DATABASE_PORT: 3306
      # DATABASE_SSL: "false"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../prod-config/Dockerfile.frontend
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_API_URL: http://localhost:1337
        VITE_BACKEND_URL: http://localhost:1337/api
        VITE_TOKEN: 934373abb10cfef6c092669619b1e4d1edf99ea6953936634d3c1a51461e4d15b2b38393c2f278088d5e152fca7159bbb55b975bebf982062328cd24a018fda0385d3c9e4e7021545af4e57c80462547bb5991c76d7314f12587e75d1bf84e85520eecc9118fce3ee65bae5554f8155ff22c3cbc843319d51987ba77ca2b4e18
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - golnet

networks:
  golnet:
    driver: bridge