name: GOL-VUE-Strapi-prod

services:
  cms:
    build:
      context: ../cms
      dockerfile: ../prod-config/Dockerfile.cms
    volumes:
      - ../cms/public/uploads:/usr/app/public/uploads
      - ../cms/.tmp:/usr/app/.tmp
    restart: unless-stopped
    networks:
      - golnet
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    environment:
      # Strapi секреты
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}

      # Настройки приложения
      NODE_ENV: ${NODE_ENV}

      # Настройки SQLite
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      DATABASE_SSL: ${DATABASE_SSL}

      # Настройки MySQL
      # DATABASE_HOST: db
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_USERNAME: ${DATABASE_USERNAME}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_CLIENT: mysql
      # DATABASE_PORT: 3306
      # DATABASE_SSL: "false"

      # === SMTP НАСТРОЙКИ ===
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_TLS_REJECT_UNAUTHORIZED: ${SMTP_TLS_REJECT_UNAUTHORIZED}
      SMTP_REQUIRE_TLS: ${SMTP_REQUIRE_TLS}
      SMTP_IGNORE_TLS: ${SMTP_IGNORE_TLS}

      SMTP_TLS_MIN_VERSION: ${SMTP_TLS_MIN_VERSION}
      SMTP_TLS_MAX_VERSION: ${SMTP_TLS_MAX_VERSION}
      SMTP_TLS_CIPHERS: ${SMTP_TLS_CIPHERS}

      SMTP_DEFAULT_FROM: ${SMTP_DEFAULT_FROM}
      SMTP_DEFAULT_REPLY_TO: ${SMTP_DEFAULT_REPLY_TO}
      SMTP_TO_ADMIN: ${SMTP_TO_ADMIN}

      SEND_EMAILS: ${SEND_EMAILS}
      EMAIL_RATE_LIMIT: ${EMAIL_RATE_LIMIT}
      EMAIL_TIMEOUT: ${EMAIL_TIMEOUT}

      EMAIL_DEBUG: ${EMAIL_DEBUG}
      EMAIL_LOGGER: ${EMAIL_LOGGER}

  frontend:
    build:
      context: ../frontend
      dockerfile: ../prod-config/Dockerfile.frontend
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${STRAPI_API_URL}
        VITE_BACKEND_URL: ${STRAPI_URL}
        VITE_TOKEN: ${STRAPI_TOKEN}
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - golnet

networks:
  golnet:
    driver: bridge