name: GOL-VUE-Strapi-prod

services:
  cms:
    build:
      context: ../cms
      dockerfile: ../prod-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms/public/uploads:/usr/app/public/uploads
      - ../cms/.tmp:/usr/app/.tmp
    restart: unless-stopped
    networks:
      - golnet
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    environment:
      # Strapi секреты
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}

      # Настройки приложения
      NODE_ENV: ${NODE_ENV}

      # Настройки SQLite
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      DATABASE_SSL: ${DATABASE_SSL}

      # Настройки MySQL
      # DATABASE_HOST: db
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_USERNAME: ${DATABASE_USERNAME}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_CLIENT: mysql
      # DATABASE_PORT: 3306
      # DATABASE_SSL: "false"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../prod-config/Dockerfile.frontend
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${STRAPI_API_URL}
        VITE_BACKEND_URL: ${STRAPI_URL}
        VITE_TOKEN: ${STRAPI_TOKEN}
    # Для Portainer (убрать если используется .env)
    env_file:
      - stack.env
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - golnet

networks:
  golnet:
    driver: bridge