FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    libvips-dev \
    python3 \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production
WORKDIR /usr/app

COPY package*.json yarn.lock* ./

RUN yarn install --frozen-lockfile --production

COPY . .

RUN yarn build

RUN mkdir -p /usr/app/.tmp /usr/app/public/uploads && \
    chown -R node:node /usr/app

# ПЕРЕКЛЮЧАЕМСЯ НА ПОЛЬЗОВАТЕЛЯ node
USER node

EXPOSE 1337

CMD ["yarn", "start"]